"""add cleanup fields to files

Revision ID: 677d7abacd54
Revises: 
Create Date: 2026-02-12 12:21:35.300549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '677d7abacd54'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('is_downloaded', sa.Boolean(), nullable=False))
    op.add_column('files', sa.Column('downloaded_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('files', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False))
    op.create_index(op.f('ix_files_expires_at'), 'files', ['expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_files_expires_at'), table_name='files')
    op.drop_column('files', 'expires_at')
    op.drop_column('files', 'downloaded_at')
    op.drop_column('files', 'is_downloaded')
    # ### end Alembic commands ###
